Loading data from case7_bnb_cleaned.csv...
Traceback (most recent call last):
  File "/home/ariadna/Documentos/TFG/bin/heatmap.py", line 12, in <module>
    data = pd.read_csv(args.input)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariadna/Documentos/TFG/env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariadna/Documentos/TFG/env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariadna/Documentos/TFG/env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariadna/Documentos/TFG/env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/ariadna/Documentos/TFG/env/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'case7_bnb_cleaned.csv'

real	0m0,873s
user	0m3,253s
sys	0m0,105s
